### PR TITLE
Remove @includes From flex Properties

### PR DESCRIPTION
**Pull request by arelia**
**Purpose**
Removes `@includes` from `flex` properties

**Reasons:**
- Bourbon will deprecate these mixins: http://bourbon.io/docs/#flexbox
- [We only support IE11+](https://github.com/cbdr/employer#browser-testing), which supports standard properties, albeit with bugs: http://caniuse.com/#search=flexbox
- We have autoprefixer for our CSS output, which complains about the CSS output added by the mixins
image
- It will also eliminate deprecation errors in Employer
image
- Cleaner code

**JIRA**
n/a

**Changes**
* Improvements and fixes
 * 

* Changes to developer setup/environment
  * 

* Architectural changes
  * 

* Migrations or Steps to Take on Production
  * 
  
* Library changes
  * 

* Side effects
  * This likely breaks (or breaks *more*) layouts for IE10 and below

**Screenshots**
n/a

**Feature Server**
http://web.employer-6.development.c66.me/

**How to Verify These Changes**
* Specific pages to visit
n/a

* Steps to take
  * Check several random pages (**on IE11 and Safari in particular**) to make sure the lack of fallback properties doesn't break anything
  * There should be no differences from `develop`
  * Here's a list of one of each page type, with a few key/recent pages in bold

**http://web.employer-6.development.c66.me/**
**http://web.employer-6.development.c66.me/recruiting-solutions/post-your-job-right-now**
**http://web.employer-6.development.c66.me/recruiting-solutions/resume-database**
**http://web.employer-6.development.c66.me/recruiting-solutions/small-business-subscription-plans-and-pricing**
**http://web.employer-6.development.c66.me/company/why-careerbuilder**
**http://web.employer-6.development.c66.me/recruiting-solutions/applicant-tracking/dummy**

http://web.employer-6.development.c66.me/promotions
http://web.employer-6.development.c66.me/recruiting-solutions
http://web.employer-6.development.c66.me/dy-test
http://web.employer-6.development.c66.me/company/leadership
http://web.employer-6.development.c66.me/all-products-sitemap
http://web.employer-6.development.c66.me/employment-screening
http://web.employer-6.development.c66.me/portal/epwhg
http://web.employer-6.development.c66.me/recruiting-solutions/display-advertising
http://web.employer-6.development.c66.me/recruiting-solutions/talent-gather
http://web.employer-6.development.c66.me/recruiting-solutions/supply-and-demand
http://web.employer-6.development.c66.me/recruiting-solutions/post-job-ppc

* Responsive considerations
  * Check mobile devices to make sure the lack of fallback properties doesn't break anything

**Relevant PRs/Dependencies**
  * n/a

**Additional Information**

### CODE REVIEW

**Comment by MKwenhua** [comment]
@arelia So we are going to disregard all Netscape users?

**Comment by arelia** [comment]
@MKwenhua yes

and we'll point and laugh at them as well

**Comment by toastercup** [comment]
@arelia I wasn't aware we were already using Autoprefixer.. when/how did that get added? In that case, we should definitely remove these prefixer mixins, as autoprefixer should already be handling these older browsers. cc @mrfantasticwonders

**Comment by arelia** [comment]
@toastercup autoprefixer was added in #120 (and now that I look at [that commit](https://github.com/cb-talent-development/employer-style-base/blame/master/package.json#L28), autoprefixer wasn't required). 

Some things from that PR:
* Fractal needed CSS so that it could render components with our fonts and other styles
* That PR adds compilation into CSS + running the CSS through Autoprefixer. Employer is not getting any of the Autoprefixed styles because Employer still uses the uncompiled Sass. 

So Employer still needs the flex fallbacks OR looking into the broken parts and [fixing them](https://github.com/philipwalton/flexbugs). For what's broken on iOS Safari there are probably known fixes. For older IE I expect it to just be broken. 

But this PR isn't from a story or a priority, so I agree with David on keeping it in mind but holding off on getting it merged.

**Comment by toastercup** [comment]
@arelia Thanks for the information - we'll probably create a refactor story to transition fully from Bourbon v4 -> v5 and add Autoprefixer to our pipeline.

**Comment by mrfantasticwonders** [comment]
@toastercup We might be able to merge this story a little sooner than later (mainly to keep the number of merge conflicts at a minimum) if Justin and I find out that most of our Safari users are on 10.2 and up. 

As Arelia said, we're not concerning ourselves with IE users who are not at least using 11. If that's the case, then I would have no problem merging this story and we can continue to use the flex properties without their includes until we decide to transition to Bourbon v5.

**Pull request closed without merging**
